// export const PREFIX = 'frames'

// export const INCREMENT_ENTHUSIASM = `${PREFIX}/INCREMENT_ENTHUSIASM`;
// export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


// export const DECREMENT_ENTHUSIASM = `${PREFIX}/DECREMENT_ENTHUSIASM`;
// export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
